# Dockerfile for production deployment
# Using a aws docker image
FROM public.ecr.aws/lambda/python:3.9

# Copy function code
COPY main.py ${LAMBDA_TASK_ROOT}/app.py

# Install the function's dependencies using file requirements.txt

COPY requirements.txt  .
RUN  pip3 install --no-cache-dir -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Set the CMD to the handler (mangum)
CMD [ "app.handler" ]